---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # set global chunk option
```


```{r libraries, message=FALSE}
library(tidyverse)      # Tidyverse for data manipulation
library(lubridate)     # Working with dates
library(knitr)        # Kniting
library(kableExtra)   # Printing nice tables
library(magrittr)     # 
```




## Loading and preprocessing the data

```{r loadpreprocessdata, include=FALSE}

#-- Load the data
activity <- read_csv("./data/activity.csv")

```


```{r processdata, echo=F, fig.height=4, fig.width=5}
#-- Have a look at raw data

print(activity, n =10)
View(activity)
glimpse(activity)   
dim(activity)
sample_n(activity, size = 10)

#-- Summary of the dataset
summary(activity)

#-- Missing values per variable 
sapply(activity, function(x) sum(is.na(x)))

#-- Simple plots for visualizations 

ggplot(activity, aes(steps)) + geom_histogram() + theme_bw()
  

```



## What is mean total number of steps taken per day?


```{r histogram1, message=FALSE, fig.height=4, fig.width=5}
#-- Histogram of total number of steps taken each day
activity <- activity %>% 
  group_by(date) %>% 
  mutate(total_steps = sum(steps))

plot1 <- ggplot(activity, aes(total_steps)) + geom_histogram() + theme_bw()
plot1 + ggtitle("Histogram of the total number of steps each day") + xlab("Total number of steps") + ylab("Count")
plot1
```


```{r median_steps, message=FALSE}
#--- Mean and median number of steps taken each day
activity %>% 
  group_by(date) %>% 
  summarise(
    mean_steps = mean(steps),
    median_steps = median(steps)
  ) %>% 
  kable() %>% 
  kable_styling() %>% 
  scroll_box(width = "500px", height = "500px")
 

```


## What is the average daily activity pattern?


```{r time-series, message=F}
#--- Calculate the average number of steps per day

activity <- activity %>% 
  group_by(date) %>% 
  mutate(avg_steps = mean(steps))
#---- Plot the time interval(x axis) and avg_steps(y)


plot2 <- plot(activity$interval, activity$avg_steps, type = 'l',
              main = "Time series plot of interval and number steps",
              xlab = "Interval",
              ylab = "Average number os steps")
plot2 


```


```{r max_steps, message = F}
#--- The 5-minute interval that, on average, contains the maximum number of steps
activity %>% 
  group_by(date) %>% 
  mutate(max_steps =max(steps)) %>% 
  select(interval, max_steps, steps) %>% 
  filter(!is.na(max_steps)) %>% 
  arrange(desc(steps)) %>% 
  distinct(date, max_steps, .keep_all = T) %>% 
  kable() %>% 
  kable_styling() %>% 
  scroll_box(width = "500px", height = "500px")

  
```



## Imputing missing values

```{r impute_miss}

#--- Impute missing for each day using mean 
activity_nomissing <-  activity%>% 
  group_by(date) %>% 
  mutate(steps = replace(steps,
                         is.na(steps), mean(steps, na.rm = T)),
         interval = replace(interval,
                         is.na(interval), mean(interval, na.rm = T))) %>% ungroup()

#--- For the remaining missing impute for the whole dataset
activity_nomissing <-  activity_nomissing %>% 
  mutate(steps = replace(steps,
                         is.na(steps), mean(steps, na.rm = T))) %>% 
  select(-avg_steps)

#--- Check both datasets
summary(activity_nomissing)
summary(activity)
```


## Are there differences in activity patterns between weekdays and weekends?
